version: 2
sources:
  - name: gh_archive_staging
    tables:
        - name: raw_data_v3

models:
  - name: stg_commits
    description: >
      GitHub commits
  - name: stg_pullrequests
    description: >
      GitHub pull requests 
