version: 2
sources:
  - name: gh_archive_staging
    tables:
        - name: raw_data_v3

models:
  - name: stg_commits
    description: >
      GitHub commits
  - name: stg_pullrequests
    description: >
      GitHub pull request
  - name: stg_users
    description: >
      GitHub users
    columns: 
    - name: user_id
      tests:
      - not_null
      # - unique
  - name: stg_org
    description: >
      Organizations on Github
    columns: 
    - name: org_id
      tests:
      - not_null
      # - unique
    
