version: 1
sources:
  - name: staging
    database: github_data_staging
    schema: dbt_dwh
    tables:
        - name: dwh_days

models:
  - name: stg_commits
    description: >
      GitHub commits
