version: 2
sources:
  - name: gh_archive_staging
    tables:
        - name: raw_data_v3

models:
  - name: stg_gh_archive_partition.sql
    description: >
      GitHub Archive event data partitioned by created date
  - name: stg_users
    description: >
      GitHub users
    columns: 
    - name: user_id
      tests:
      - not_null
      - unique
  - name: stg_org
    description: >
      Organizations on Github
    columns: 
    - name: org_id
      tests:
      - not_null
      - unique
    
